export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const REST_CALL_BEGIN = 'REST_CALL_BEGIN';
export const REST_CALL_ERROR = 'REST_CALL_ERROR';
export const REST_CALL_SUCCESS = 'REST_CALL_SUCCESS';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';