export const FETCH_NOCONTENT = 'FETCH_NOCONTENT';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ONE_SUCCESS = 'FETCH_ONE_SUCCESS';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';

export const REST_CALL_BEGIN = 'REST_CALL_BEGIN';
export const REST_CALL_ERROR = 'REST_CALL_ERROR';
export const REST_CALL_SUCCESS = 'REST_CALL_SUCCESS';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_WARNING = 'NOTIFICATION_WARNING';

export const HTTP_STATUS_404 = 404;
